### ISSUE TITLE
Port support?

### ISSUE THREAD

**Issue by codydjango** [nordsoftware/lumen-cors#33]
### What did you expect to happen?
By defining `localhost:8090` in my allow_origins, I'd be able to receive requests from localhost:8090. 

### What actually happened?
Origin is not allowed

### What versions of PHP, Lumen and this module are you using?

```json
"php": ">=5.6.4",
"laravel/lumen-framework": "5.4.*",
"nordsoftware/lumen-cors": "^2.1"
```

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.
it's the configuration: 
    
```php
'allow_origins' => ['*.website.com', 'localhost:8090'],
```

**Comment by Jalle19** [comment]
What does the generated header look like?

**Comment by Jalle19** [comment]
I had a closer look and concluded that there are two issues with your configuration:

1. You cannot use wild-cards like `*.website.com`, allowed origins must be either a single wild-card (i.e. `*`) or a list of exact `protocol + domain [+ port]` strings. This brings us to:

2. If you want to allow requests from `http://localhost:8090`, you must specify `http://localhost:8090` in `allow_origins`. Just `localhost:8090` is not enough and you will get a 403 Forbidden response, because the browser sends `http://localhost:8090`.

Hope that helps!

**Comment by codydjango** [comment]
Totally. Thanks so much for the quick response.
